"""
Professional File Format & Export Engine
مدیریت ذخیره‌سازی فیزیکی فایل‌های مهندسی (COE, MIF, HEX, VHD) با رعایت استانداردهای صنعتی
"""

import os
import sys
from datetime import datetime

# اضافه کردن مسیر ریشه برای دسترسی به تنظیمات و مدیریت خطا
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from core.error_handler import error_handler

class FileFormatEngine:
    def __init__(self):
        self.export_base_path = config.PATHS["EXPORTS"]

    def _ensure_dir(self, sub_dir=None):
        """اطمینان از وجود دایرکتوری خروجی"""
        path = self.export_base_path
        if sub_dir:
            path = os.path.join(path, sub_dir)
        
        if not os.path.exists(path):
            os.makedirs(path, exist_ok=True)
        return path

    def save_file(self, content, filename, sub_dir=None, extension=None):
        """
        ذخیره محتوا در فایل با مدیریت خطا و مسیر
        content: متن فایل
        filename: نام فایل (بدون پسوند یا با پسوند)
        extension: پسوند فایل (مثلاً .coe)
        """
        try:
            target_dir = self._ensure_dir(sub_dir)
            
            # جدا کردن نام و پسوند اگر در نام فایل وجود داشته باشد
            name, ext = os.path.splitext(filename)
            final_extension = extension or ext or ".txt"
            full_filename = f"{name}{final_extension}"
            
            file_path = os.path.join(target_dir, full_filename)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            return True, file_path
        
        except Exception as e:
            error_handler.log_error(f"Failed to save file {filename}: {str(e)}")
            return False, str(e)

    def generate_hdl_package(self, constants_dict, package_name="Global_Defs"):
        """
        تولید یک پکیج VHDL شامل ثابت‌های محاسباتی
        (بسیار مفید برای انتقال ضرایب فیلتر به سخت‌افزار)
        """
        vhd_content = f"-- Auto-generated by Digital Engineer's Suite\n"
        vhd_content += f"-- Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        vhd_content += "library ieee;\nuse ieee.std_logic_1164.all;\n\n"
        vhd_content += f"package {package_name} is\n"
        
        for name, value in constants_dict.items():
            vhd_content += f"    {value}\n"
            
        vhd_content += f"end package {package_name};"
        return vhd_content

    def get_last_exports(self, limit=5):
        """دریافت لیست آخرین فایل‌های صادر شده برای نمایش در UI"""
        if not os.path.exists(self.export_base_path):
            return []
        
        files = [os.path.join(self.export_base_path, f) for f in os.listdir(self.export_base_path) 
                 if os.path.isfile(os.path.join(self.export_base_path, f))]
        
        # مرتب‌سازی بر اساس زمان تغییر
        files.sort(key=os.path.getmtime, reverse=True)
        return [os.path.basename(f) for f in files[:limit]]

# ایجاد نمونه سراسری
file_engine = FileFormatEngine()
