"""
Verilog Code Templates Bank
مجموعه قالب‌های استاندارد برای تولید کدهای Verilog و SystemVerilog
"""

# قالب هدر استاندارد برای فایل‌های Verilog
HEADER_TEMPLATE = """// =============================================================
// File Name: {file_name}
// Design Name: {design_name}
// Author: {author}
// Date: {date}
// Generated by: Digital Engineer's Suite Pro
// =============================================================
`timescale 1ns / 1ps

"""

# قالب ساختار اصلی Module
MODULE_TEMPLATE = """module {module_name} (
    input wire clk,
    input wire rst,
    {ports}
);

    // Internal signals and registers
    {signals}

    // Main logic
    {logic}

endmodule
"""

# قالب ماشین حالت (FSM) - مدل Verilog استاندارد
FSM_TEMPLATE = """
    // State encoding
    localparam {state_params};
    
    reg [31:0] current_state, next_state;

    // State Register Logic
    always @(posedge clk or {reset_edge} rst) begin
        if (rst == 1'b{reset_level})
            current_state <= {initial_state};
        else
            current_state <= next_state;
    end

    // Next State Logic
    always @(*) begin
        case (current_state)
            {state_cases}
            default: next_state = {initial_state};
        endcase
    end
"""

# قالب نمونه‌سازی (Instantiation)
INSTANTIATION_TEMPLATE = """
{module_name} {inst_name} (
    .clk(clk),
    .rst(rst),
    {port_map}
);
"""

# قالب تست‌بنچ (Testbench) در Verilog
TESTBENCH_TEMPLATE = """
module {module_name}_tb();

    reg clk;
    reg rst;
    {tb_signals}

    // Clock Generation
    initial begin
        clk = 0;
        forever #({clk_period}/2) clk = ~clk;
    end

    // Unit Under Test (UUT)
    {module_name} uut (
        .clk(clk),
        .rst(rst),
        {tb_port_map}
    );

    // Stimulus
    initial begin
        // Initialize Inputs
        rst = 1'b{reset_level};
        #100;
        rst = ~1'b{reset_level};
        
        {stimulus}
        
        #1000;
        $finish;
    end

endmodule
"""
