"""
VHDL Code Templates Bank
مجموعه قالب‌های استاندارد برای تولید کدهای VHDL
"""

# قالب هدر استاندارد برای تمام فایل‌ها
HEADER_TEMPLATE = """-- =============================================================
-- File Name: {file_name}
-- Design Name: {design_name}
-- Author: {author}
-- Date: {date}
-- Generated by: Digital Engineer's Suite Pro
-- =============================================================
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

"""

# قالب ساختار اصلی Entity و Architecture
ENTITY_ARCH_TEMPLATE = """entity {entity_name} is
    port (
        clk     : in  std_logic;
        rst     : in  std_logic;
        {ports}
    );
end entity {entity_name};

architecture rtl of {entity_name} is
    -- Signal declarations
    {signals}
begin
    -- Logic
    {logic}
end architecture rtl;
"""

# قالب ماشین حالت (FSM) - مدل دو پروسسی
FSM_TEMPLATE = """
    type state_type is ({states});
    signal current_state, next_state : state_type;

    -- State Register Process
    state_reg: process(clk, rst)
    begin
        if rst = '{reset_level}' then
            current_state <= {initial_state};
        elsif rising_edge(clk) then
            current_state <= next_state;
        end if;
    end process;

    -- Next State Logic Process
    comb_logic: process(current_state, {inputs})
    begin
        case current_state is
            {state_cases}
            when others =>
                next_state <= {initial_state};
        end case;
    end process;
"""

# قالب نمونه‌سازی (Instantiation)
INSTANTIATION_TEMPLATE = """
{inst_name} : entity work.{entity_name}
    port map (
        clk => clk,
        rst => rst,
        {port_map}
    );
"""

# قالب تست‌بنچ (Testbench)
TESTBENCH_TEMPLATE = """
entity {entity_name}_tb is
end entity {entity_name}_tb;

architecture sim of {entity_name}_tb is
    signal clk : std_logic := '0';
    signal rst : std_logic := '{reset_level}';
    {tb_signals}
begin
    -- Clock Generation
    clk <= not clk after {clk_period} / 2;

    -- Unit Under Test (UUT)
    uut: entity work.{entity_name}
        port map (
            clk => clk,
            rst => rst,
            {tb_port_map}
        );

    -- Stimulus Process
    stim_proc: process
    begin
        wait for 100 ns;
        rst <= not '{reset_level}';
        {stimulus}
        wait;
    end process;
end architecture sim;
"""
